import { createHash } from 'node:crypto';
import { readdir, readFile, unlink } from 'node:fs/promises';
import { relative, resolve } from 'node:path';
import { getBumpyDir, matchGlob, resolveFixedGroups } from './config.ts';
import { writeBumpFile } from './bump-file.ts';
import { readFileAtRef } from './git.ts';
import { catalogYamlFile, detectPackageManager, parseCatalogs, resolveCatalogDep } from '../utils/package-manager.ts';
import type { CatalogMap } from '../utils/package-manager.ts';
import { ensureDir, exists, readText } from '../utils/fs.ts';
import { slugify } from '../utils/names.ts';
import { DEP_TYPES } from '../types.ts';
import type { BumpyConfig, DepType, WorkspacePackage } from '../types.ts';

/**
 * Auto-generated bump files for dependency updates (Dependabot, Renovate, …).
 *
 * Modeled on the-guild-org/changesets-dependencies-action: diff each managed package's
 * `package.json` dependency fields against the base, and write one patch bump file per
 * affected package whose summary lists the changed deps. Files are named
 * deterministically (`deps-<suffix>-<pkg>.md`) and carry a marker comment, so re-running
 * regenerates them in place and removes ones that no longer apply — and never touches
 * bump files it didn't generate.
 */

export interface DependencyChange {
  name: string;
  depType: DepType;
  kind: 'added' | 'updated' | 'removed';
  /** Range before (absent for `added`) — catalog refs resolved to the catalog's range */
  from?: string;
  /** Range after (absent for `removed`) — catalog refs resolved to the catalog's range */
  to?: string;
}

/** Bump file id prefix for all auto-generated dependency bump files */
export const DEP_BUMP_FILE_PREFIX = 'deps-';

/** Frontmatter comment marking a bump file as generated — only marked files are ever deleted */
export const DEP_BUMP_FILE_MARKER = 'generated by bumpy from dependency changes — regenerated on each run';

/**
 * File id for a package's generated dependency bump file, e.g. `deps-pr42-myorg-core`.
 * `slugify` is lossy (`@org/a` and `org-a` both → `org-a`), so when a package's slug
 * collides with another managed package's, a short hash of the full name is appended.
 * Collisions are checked against all managed packages, so ids stay stable across runs.
 */
export function depBumpFileId(suffix: string, pkgName: string, allPackageNames: Iterable<string> = []): string {
  const slug = slugify(pkgName);
  let collides = false;
  for (const other of allPackageNames) {
    if (other !== pkgName && slugify(other) === slug) collides = true;
  }
  const unique = collides ? `${slug}-${createHash('sha256').update(pkgName).digest('hex').slice(0, 8)}` : slug;
  return `${DEP_BUMP_FILE_PREFIX}${slugify(suffix)}-${unique}`;
}

/**
 * The dependency fields whose changes should produce a release for this package: the
 * ones that affect what consumers install (everything not in `ignoredPackageJsonFields`),
 * plus `devDependencies` entries matching the package's `releaseTriggeringDevDeps`.
 */
function isReleaseRelevantDep(depType: DepType, depName: string, pkg: WorkspacePackage, ignored: Set<string>): boolean {
  if (!ignored.has(depType)) return true;
  if (depType !== 'devDependencies') return false;
  return (pkg.bumpy?.releaseTriggeringDevDeps ?? []).some((pattern) => matchGlob(depName, pattern));
}

function resolveRange(depName: string, range: string | undefined, catalogs: CatalogMap): string | undefined {
  if (range === undefined) return undefined;
  return resolveCatalogDep(depName, range, catalogs) ?? range;
}

async function loadCatalogsAt(rootDir: string, ref: string | null): Promise<CatalogMap> {
  const pm = await detectPackageManager(rootDir);
  const yamlFile = catalogYamlFile(pm);
  if (ref) {
    return parseCatalogs(
      yamlFile ? readFileAtRef(rootDir, ref, yamlFile) : null,
      readFileAtRef(rootDir, ref, 'package.json'),
    );
  }
  const read = async (file: string) =>
    (await exists(resolve(rootDir, file))) ? readText(resolve(rootDir, file)) : null;
  return parseCatalogs(yamlFile ? await read(yamlFile) : null, await read('package.json'));
}

/**
 * Diff the release-relevant dependencies of every managed package between `baseRef` and
 * the working tree — mirroring what `bumpy check` treats as release-affecting, so the
 * generated files cover exactly what the check requires. Packages that are new on this
 * branch are skipped. Catalog refs (`catalog:`) are resolved on both sides, so a
 * catalog-only update is reported against every package that uses it.
 */
export async function detectDependencyChanges(
  rootDir: string,
  config: BumpyConfig,
  packages: Map<string, WorkspacePackage>,
  baseRef: string,
): Promise<Map<string, DependencyChange[]>> {
  const ignored = new Set(config.ignoredPackageJsonFields ?? ['devDependencies']);
  const [beforeCatalogs, afterCatalogs] = await Promise.all([
    loadCatalogsAt(rootDir, baseRef),
    loadCatalogsAt(rootDir, null),
  ]);

  const result = new Map<string, DependencyChange[]>();
  for (const [name, pkg] of packages) {
    const pkgRelDir = relative(rootDir, pkg.dir);
    const relPath = pkgRelDir ? `${pkgRelDir}/package.json` : 'package.json';
    const beforeRaw = readFileAtRef(rootDir, baseRef, relPath);
    if (beforeRaw == null) continue; // new package — not a dependency update
    let before: Record<string, unknown>;
    try {
      before = JSON.parse(beforeRaw);
    } catch {
      continue;
    }

    const changes: DependencyChange[] = [];
    for (const depType of DEP_TYPES) {
      const beforeDeps = (before[depType] ?? {}) as Record<string, string>;
      const afterDeps = pkg[depType] ?? {};
      const depNames = [...new Set([...Object.keys(beforeDeps), ...Object.keys(afterDeps)])].sort();
      for (const depName of depNames) {
        if (!isReleaseRelevantDep(depType, depName, pkg, ignored)) continue;
        const rawFrom = beforeDeps[depName];
        const rawTo = afterDeps[depName];
        const from = resolveRange(depName, rawFrom, beforeCatalogs);
        const to = resolveRange(depName, rawTo, afterCatalogs);
        if (from === to) continue;
        const kind = from === undefined ? 'added' : to === undefined ? 'removed' : 'updated';
        changes.push({ name: depName, depType, kind, from, to });
      }
    }
    if (changes.length > 0) result.set(name, changes);
  }
  return result;
}

/** Best-effort `x.y.z` from a range like `^1.2` or `~1.2.3-beta.1`, for the npm link */
function coerceVersion(range: string): string | null {
  const match = range.match(/(\d+)(?:\.(\d+))?(?:\.(\d+))?(-[0-9A-Za-z.-]+)?/);
  if (!match) return null;
  return `${match[1]}.${match[2] ?? 0}.${match[3] ?? 0}${match[4] ?? ''}`;
}

function formatDep(name: string, range: string): string {
  const label = `\`${name}@${range}\``;
  // Only link registry ranges — not git/file/link/npm-alias specifiers
  const version = range.includes(':') || range.includes('/') ? null : coerceVersion(range);
  return version ? `[${label} ↗︎](https://www.npmjs.com/package/${name}/v/${version})` : label;
}

/** One changelog line per changed dependency (same wording as changesets-dependencies-action) */
export function formatDependencyChange(change: DependencyChange): string {
  switch (change.kind) {
    case 'added':
      return `Added dependency ${formatDep(change.name, change.to!)} (to \`${change.depType}\`)`;
    case 'updated':
      return `Updated dependency ${formatDep(change.name, change.to!)} (from \`${change.from}\`, in \`${change.depType}\`)`;
    case 'removed':
      return `Removed dependency ${formatDep(change.name, change.from!)} (from \`${change.depType}\`)`;
  }
}

export function formatDependencySummary(changes: DependencyChange[], viaPackage?: string): string {
  const heading = viaPackage ? `Dependency updates in \`${viaPackage}\`:` : 'Dependency updates:';
  return [heading, '', ...changes.map((c) => `- ${formatDependencyChange(c)}`)].join('\n');
}

export interface PlannedDependencyBumpFile {
  id: string;
  /** Package whose dependencies changed */
  pkgName: string;
  /** Package that receives the patch bump — differs for `directBump: false` packages */
  releaseName: string;
  summary: string;
}

export interface DependencyBumpFilePlan {
  files: PlannedDependencyBumpFile[];
  /** `directBump: false` packages with dependency changes but no fixed-group member to carry the bump */
  uncoverable: string[];
}

/**
 * Turn detected changes into bump files. A `directBump: false` package can't be bumped
 * itself — its changes ship by bumping another member of its fixed group (see
 * `resolveDirectBumpCoverage` in `bumpy check`), so the bump goes on the first bumpable
 * member. With no such member it's reported as `uncoverable`.
 */
export function planDependencyBumpFiles(
  changes: Map<string, DependencyChange[]>,
  packages: Map<string, WorkspacePackage>,
  config: BumpyConfig,
  suffix: string,
): DependencyBumpFilePlan {
  const fixedGroups = resolveFixedGroups(config, packages.keys());
  const files: PlannedDependencyBumpFile[] = [];
  const uncoverable: string[] = [];

  for (const [pkgName, pkgChanges] of changes) {
    let releaseName = pkgName;
    if (packages.get(pkgName)?.bumpy?.directBump === false) {
      const group = fixedGroups.find((members) => members.includes(pkgName)) ?? [];
      const driver = group.filter((m) => m !== pkgName && packages.get(m)?.bumpy?.directBump !== false).sort()[0];
      if (!driver) {
        uncoverable.push(pkgName);
        continue;
      }
      releaseName = driver;
    }
    files.push({
      id: depBumpFileId(suffix, pkgName, packages.keys()),
      pkgName,
      releaseName,
      summary: formatDependencySummary(pkgChanges, releaseName === pkgName ? undefined : pkgName),
    });
  }
  return { files, uncoverable };
}

/** Error text for `directBump: false` packages whose dependency changes can't be covered */
export function formatUncoverableError(names: string[]): string {
  return (
    `Dependency changes in ${names.map((n) => `"${n}"`).join(', ')} can't be covered automatically — ` +
    '`directBump: false` packages only release via a fixed-group member or propagation, and none is configured.\n' +
    '  Add the package to a fixed group with a bumpable member, or add a bump file for its cascade source by hand.'
  );
}

export interface SyncDependencyBumpFilesResult {
  /** Bump file ids written (created or rewritten) */
  written: string[];
  /** Bump file ids removed because their package no longer has dependency changes */
  removed: string[];
}

/** Whether an existing bump file was written by `syncDependencyBumpFiles` */
async function isGeneratedDepBumpFile(filePath: string): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    const frontmatter = content.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';
    return frontmatter.split('\n').some((line) => line.trim() === `# ${DEP_BUMP_FILE_MARKER}`);
  } catch {
    return false;
  }
}

/**
 * Write the planned bump files, and delete previously generated files (same `suffix`)
 * for packages that no longer have changes. A file is only deleted when it is
 * positively ours: same prefix, carries the generated marker, and was added on this
 * branch (absent at `baseRef`) — so hand-written files and already-merged files from
 * other branches are never touched.
 */
export async function syncDependencyBumpFiles(
  rootDir: string,
  plan: DependencyBumpFilePlan,
  suffix: string,
  baseRef: string,
): Promise<SyncDependencyBumpFilesResult> {
  const bumpyDir = getBumpyDir(rootDir);
  await ensureDir(bumpyDir);

  const written: string[] = [];
  for (const file of plan.files) {
    await writeBumpFile(
      rootDir,
      file.id,
      [{ name: file.releaseName, type: 'patch' }],
      file.summary,
      DEP_BUMP_FILE_MARKER,
    );
    written.push(file.id);
  }

  const stalePrefix = `${DEP_BUMP_FILE_PREFIX}${slugify(suffix)}-`;
  const removed: string[] = [];
  for (const file of await readdir(bumpyDir)) {
    if (!file.endsWith('.md') || !file.startsWith(stalePrefix)) continue;
    const id = file.slice(0, -'.md'.length);
    if (written.includes(id)) continue;
    const filePath = resolve(bumpyDir, file);
    if (!(await isGeneratedDepBumpFile(filePath))) continue;
    if (readFileAtRef(rootDir, baseRef, relative(rootDir, filePath)) != null) continue;
    await unlink(filePath);
    removed.push(id);
  }

  return { written, removed };
}
