name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write # required for npm trusted publishing (OIDC)
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      # Node.js (npm) is needed for npm publish
      - uses: actions/setup-node@v6
        with:
          node-version: lts/* # newer node needed for OIDC
      - run: bun install

      # --- You wont need this part ---
      # Build first since we use the local built version of bumpy instead of the published one
      - run: bun run --filter @varlock/bumpy build
      # run bun install again to make the now built CLI available
      - run: bun install
      # -------------------------------

      # 🐸 This is the important part - creates/updates release PR when PRs merge to main, publishes packages when release PR is merged
      - run: bunx @varlock/bumpy ci release
        env:
          GH_TOKEN: ${{ github.token }}
          BUMPY_GH_TOKEN: ${{ secrets.BUMPY_GH_TOKEN }} # <- PAT so that version PR triggers CI
